apiVersion: v1
kind: Service
metadata:
  name: dynamodb-local
spec:
  type: NodePort  # Change from ClusterIP to NodePort
  selector:
    app: dynamodb-local
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 31000  # Specify a node port within the allowable range
