apiVersion: v1
kind: Service
metadata:
  name: streamlit-dynamodb-app
spec:
  type: NodePort
  selector:
    app: streamlit-dynamodb-app
  ports:
  - port: 8501
    targetPort: 8501
    nodePort: 30001  # This allows you to access the service on this specific port
